esphome:
  name: $name
  friendly_name: ${friendly_name}
  
  project:
    name: $project_name
    version: $project_version

esp32:  
  board: wesp32
  framework:
    type: esp-idf
    version: recommended

substitutions:
  status_led_inverted: "false"